
services:
  web:
    build: .
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    networks:
       - ecommerce-network 
    env_file: .env

  db:
    image: mysql:8
    container_name: ecommerce-db
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}

    volumes:
      - ecommerce-db:/var/lib/mysql
      
    ports:
      - "3306:3306"
    
    networks:
      - ecommerce-network

volumes:
  ecommerce-db:

networks:
  ecommerce-network:
    driver: bridge  

      

